version: '2'
services:
  db:
    image: mysql:8
    container_name: node-express-sequelize-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    env_file: ./app/.env

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: node-express-sequelize:1
    container_name: node-express-sequelize
    ports:
      - 3000:3000
    env_file: ./app/.env
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db
    command: "nodemon src/server.ts --watch 'src/**/*.ts' --exec 'ts-node'"
